title: YoungChanYoo
description: Security Engineer
site_title: '@TOSS_PORTFOLIO'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Personalization
github_username: wasd132
blog_url: 
email: wasd13579@gmail.com
phone: 010-1234-5678
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 