title: YoungChanYoo
description: Security Engineer
short_bio: "클라우드 네이티브 환경에서 Zero Trust와 AI 위협 인텔리전스를 접목한 프로젝트를 수행하며 빠르게 성장하는 신입 보안 엔지니어입니다."
site_title: '@TOSS_PORTFOLIO'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Personalization
github_username: wasd132
blog_url: 
email: wasd13579@gmail.com
phone: 010-7502-3370
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 

# Rebuild trigger: 2026-02-25 01:25 UTC