title: YoungChanYoo
description: Security Engineer
site_title: '@TOSS_PORTFOLIO'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: wasd132
blog_url: 
email: wasd13579@gmail.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 